// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhm6NMmIOUmSUpMFnlMa1A5ET2xazWrfo',
    appId: '1:767565989780:web:c2889b2919d0109bb83181',
    messagingSenderId: '767565989780',
    projectId: 'flowing-depot-428721-q6',
    authDomain: 'flowing-depot-428721-q6.firebaseapp.com',
    storageBucket: 'flowing-depot-428721-q6.appspot.com',
    measurementId: 'G-64VBGGWMKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOL9QSRh0o67RajYanQ2UJvdFri80V1IY',
    appId: '1:767565989780:android:34552ef3b3a0d2c4b83181',
    messagingSenderId: '767565989780',
    projectId: 'flowing-depot-428721-q6',
    storageBucket: 'flowing-depot-428721-q6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpC98aF8G119bC09T7kOye4domwZr9GAo',
    appId: '1:767565989780:ios:44a096e972176249b83181',
    messagingSenderId: '767565989780',
    projectId: 'flowing-depot-428721-q6',
    storageBucket: 'flowing-depot-428721-q6.appspot.com',
    iosBundleId: 'com.example.appPrueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpC98aF8G119bC09T7kOye4domwZr9GAo',
    appId: '1:767565989780:ios:44a096e972176249b83181',
    messagingSenderId: '767565989780',
    projectId: 'flowing-depot-428721-q6',
    storageBucket: 'flowing-depot-428721-q6.appspot.com',
    iosBundleId: 'com.example.appPrueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhm6NMmIOUmSUpMFnlMa1A5ET2xazWrfo',
    appId: '1:767565989780:web:fdfe879930f0e69db83181',
    messagingSenderId: '767565989780',
    projectId: 'flowing-depot-428721-q6',
    authDomain: 'flowing-depot-428721-q6.firebaseapp.com',
    storageBucket: 'flowing-depot-428721-q6.appspot.com',
    measurementId: 'G-6G5V9Z2PY5',
  );

}